apiVersion: v1
kind: Service
metadata:
  name: predictramservice
  namespace: predictram
  labels:
    group: predictram
spec:
  selector:
    dev: predictram
  ports:
    - name: proxymanger0
      protocol: TCP
      port: 80
      targetPort: 5000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: predictram
  namespace: predictram
  labels:
    group: predictram
spec:
  replicas: 5
  selector:
    matchLabels:
      dev: predictram
  template:
    metadata:
      labels:
        dev: predictram
    spec:
      containers:
        - name: predictramtest
          image: predictram.azurecr.io/predictram/backend
          imagePullPolicy: Always
          resources:
            requests:
              memory: "200Mi"
              # cpu: "150m"
            limits:
              memory: "300Mi"
              # cpu: "200m"
          livenessProbe: 
            httpGet:
              path: /api/logout
              port: 5000
            initialDelaySeconds: 30
            periodSeconds: 30
          volumeMounts:
            - mountPath: /usr/src/app/backend/uploads/images
              name: events
          env:
            - name: NODE_ENV
              value: production
            - name: POLYGON_WEBSOCKETPROVIDER
              value: "wss://polygon-mumbai.g.alchemy.com/v2/Go4JSZpl7WyUMDjEBdt_2sMqVYO89kKV"
            - name: KARDIAPROVIDER
              value: "https://rpc.kardiachain.io/"
            - name: PRIVATE_KEY
              value: "c3fe21d0d8def509c2315d174362126f9cd7ef640d74fdfb74d6d6aa7bf06621"
            - name: DB_URI
              value: "mongodb+srv://admin:admin@cluster0.wdfuc.mongodb.net/test?retryWrites=true&w=majority"
            - name: SCRAPPER_DB_URI
              value: mongodb://admin:admin@mongodb-service.mongodb:27017/scrapper?authSource=admin
            - name: SECRET
              value: "lol"
            - name: GOOGLE_CLIENT_ID
              value: "424759558013-9jc5r2tgae4es9hcugvgpeehm70bmk34.apps.googleusercontent.com"
            - name: GOOGLE_CLIENT_SECRET
              value: "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"
            - name: LINKEDIN_KEY
              value: "78cjqr9x4ojtoe"
            - name: LINKEDIN_SECRET
              value: "QcSxlwwFdIpuzmfz"
            - name: AWS_ACCESS_KEY_ID
              value: AKIA2NA3NG66ZGQ45JXO
            - name: AWS_SECRET_ACCESS_KEY
              value: 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
            - name: PORT
              value: "5000"
            - name: POLYGON_FACTORY_ADDRESS
              value: "0x47bb7fAB740cE78bDa90564aD4B14f51DD780331"
            - name: KARDIA_FACTORY_ADDRESS
              value: "0xcB136aCe2E40029337607a41CB73bb308cc4e1C1"
            - name: CONTRACT_OWNER_ADDRESS
              value: "0x79BF6Ab2d78D81da7d7E91990a25A81e93724a60"
      volumes:
        - name: events
          persistentVolumeClaim:
            claimName: predictramfile-pvc