const SECTORS = [
  "Information Technology Services",
  "Other Industrial Metals & Mining",
  "Thermal Coal",
  "Publishing",
  "Capital Markets",
  "Oil & Gas Refining & Marketing",
  "Specialty Chemicals",
  "Drug Manufacturers - Specialty & Generic",
  "Utilities - Regulated Gas",
  "Oil & Gas E&P",
  "Utilities—Regulated Electric",
  "Metal Fabrication",
  "Specialty Business Services",
  "Marine Shipping",
  "Oil & Gas Integrated",
  "Tobacco",
  "Chemicals",
  "Textile Manufacturing",
  "Auto Parts",
  "Real Estate Services",
  "Financial Conglomerates",
  "Building Materials",
  "Paper & Paper Products",
  "Utilities—Independent Power Producers",
  "Utilities - Regulated Electric",
  "Software—Infrastructure",
  "Agricultural Inputs",
  "Confectioners",
  "Steel",
  "Credit Services",
  "Engineering & Construction",
  "Apparel Manufacturing",
  "Asset Management",
  "Conglomerates",
  "Diagnostics & Research",
  "Oil & Gas Equipment & Services",
  "Farm & Heavy Construction Machinery",
  "Integrated Freight & Logistics",
  "Broadcasting",
  "Banks - Regional",
  "Real Estate—Development",
  "Farm Products",
  "Packaged Foods",
  "Lodging",
  "Electrical Equipment & Parts",
  "Banks—Regional",
  "Real Estate - Development",
  "Drug Manufacturers—General",
  "Household & Personal Products",
  "Auto Manufacturers",
  "Specialty Industrial Machinery",
  "Utilities—Renewable",
  "Packaging & Containers",
  "Luxury Goods",
  "Utilities—Regulated Gas",
  "Insurance - Reinsurance",
  "Entertainment",
  "Footwear & Accessories",
  "Drug Manufacturers—Specialty & Generic",
  "Mortgage Finance",
  "Building Products & Equipment",
  "Railroads",
  "Staffing & Employment Services",
  "Communication Equipment",
  "Education & Training Services",
  "Electronics & Computer Distribution",
  "Financial Data & Stock Exchanges",
  "Drug Manufacturers - General",
  "Aerospace & Defense",
  "Aluminum",
  "Furnishings, Fixtures & Appliances",
  "Telecom Services",
  "Restaurants",
  "Software—Application",
  "Tools & Accessories",
  "Beverages - Wineries & Distilleries",
  "Internet Content & Information",
  "Resorts & Casinos",
  "Business Equipment & Supplies",
  "Insurance—Diversified",
  "Beverages—Wineries & Distilleries",
  "Internet Retail",
  "Lumber & Wood Production",
  "Trucking",
  "Insurance - Diversified",
  "Biotechnology",
  "Computer Hardware",
  "Advertising Agencies",
  "Rental & Leasing Services",
  "Software - Application",
  "Beverages—Brewers",
  "Medical Care Facilities",
  "Apparel Retail",
  "Infrastructure Operations",
  "Insurance—Life",
  "Home Improvement Retail",
  "Insurance - Life",
  "Copper",
  "Leisure",
  "Security & Protection Services",
  "Auto & Truck Dealerships",
  "Electronic Components",
  "Pollution & Treatment Controls",
  "Real Estate—Diversified",
  "Medical Instruments & Supplies",
  "Travel Services",
  "Airports & Air Services",
  "Solar",
  "Beverages—Non-Alcoholic",
  "Consumer Electronics",
  "Department Stores",
  "Others",
  "Airlines",
  "Utilities - Independent Power Producers",
  "Discount Stores",
  "Utilities - Renewable",
  "Waste Management",
  "Food Distribution",
  "Scientific & Technical Instruments",
  "Consulting Services",
  "Electronic Gaming & Multimedia",
  "Pharmaceutical Retailers",
  "Medical Devices",
  "Specialty Retail",
  "Shell Companies",
  "ETF",
  "Real Estate - Diversified",
  "Insurance Brokers",
  "Software - Infrastructure",
  "Oil & Gas Drilling"
];

module.exports = {
  SECTORS,
};
